// <auto-generated />
using System;
using Docker.AutoDl.Database.SqLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraktDl.Business.Database.SqLite;

namespace Docker.AutoDl.Database.SqLite.Migrations
{
    [DbContext(typeof(SqLiteContext))]
    partial class SqLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029");

            modelBuilder.Entity("Docker.AutoDl.Database.SqLite.BlackListShowSqLite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Entire");

                    b.Property<int?>("Season");

                    b.Property<string>("SerieName");

                    b.Property<uint>("TraktShowId");

                    b.HasKey("Id");

                    b.HasIndex("TraktShowId", "Season")
                        .IsUnique();

                    b.ToTable("BlackListShow");
                });
#pragma warning restore 612, 618
        }
    }
}
